name: CI

on:
  push:
    branches:
      - '**'  
jobs:
  pruebas-unitarias:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: unit tests
        run:  mvn test

  empaquetar:
    runs-on: self-hosted
    needs: pruebas-unitarias
    steps:
      - name: build
        run: mvn package -DskipTests=true

  pruebas-funcionales:
    runs-on: self-hosted
    needs: empaquetar
    steps:
      - name: test
        run: |
          cp -r target/Baloncesto /usr/local/tomcat/webapps
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
          mvn failsafe:integration-test failsafe:verify

  calidad-codigo:
    runs-on: self-hosted
    needs: empaquetar
    steps:
      - name: qa
        run: mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000  Dsonar.qualitygate.wait=true Dsonar.login=admin -Dsonar.password=admin

  despliegue-host-heroku:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: echo "despliegue-host-heroku"
